1)

In [ ]:
import pandas as pd

In [ ]:
file_path = 'diabetes.csv'
diabetes_df = pd.read_csv(file_path)
diabetes_df.head(),diabetes_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


(   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
 0            6      148             72             35        0  33.6   
 1            1       85             66             29        0  26.6   
 2            8      183             64              0        0  23.3   
 3            1       89             66             23       94  28.1   
 4            0      137             40             35      168  43.1   
 
    DiabetesPedigreeFunction  Age  Outcome  
 0                     0.627   50        1  
 1                     0.351   31        0  
 2                     0.672   32        1  
 3                     0.167   21        0  
 4                     2.288   33        1  ,
 None)

In [15]:
P_Diabetes = diabetes_df['Outcome'].mean()
P_NoDiabetes = 1 - P_Diabetes

In [16]:
high_glucose_threshold = 140

In [17]:
P_HighGlucose_Diabetes = diabetes_df[(diabetes_df['Glucose'] > high_glucose_threshold) & (diabetes_df['Outcome'] == 1)].shape[0] / diabetes_df[diabetes_df['Outcome'] == 1].shape[0]
P_HighGlucose_NoDiabetes = diabetes_df[(diabetes_df['Glucose'] > high_glucose_threshold) & (diabetes_df['Outcome'] == 0)].shape[0] / diabetes_df[diabetes_df['Outcome'] == 0].shape[0]

In [18]:
P_HighGlucose = diabetes_df[diabetes_df['Glucose'] > high_glucose_threshold].shape[0] / diabetes_df.shape[0]

In [19]:
P_Diabetes_HighGlucose = (P_HighGlucose_Diabetes * P_Diabetes) / P_HighGlucose

In [2]:
import numpy as np
A = np.array([[4, 2, 1], [2, 3, 1], [1, 1, 2]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)

Eigenvalues: [6.04891734 1.64310413 1.30797853]
Eigenvectors: [[ 0.73697623  0.59100905  0.32798528]
 [ 0.59100905 -0.32798528 -0.73697623]
 [ 0.32798528 -0.73697623  0.59100905]]


In [20]:
P_Diabetes_HighGlucose

0.6874999999999999

In [3]:
determinant = np.linalg.det(A)
if determinant != 0:
    inverse = np.linalg.inv(A)
else:
    inverse = None
print("Determinant:", determinant)
print("Inverse:", inverse)

Determinant: 13.0
Inverse: [[ 0.38461538 -0.23076923 -0.07692308]
 [-0.23076923  0.53846154 -0.15384615]
 [-0.07692308 -0.15384615  0.61538462]]


In [4]:
import scipy.stats as stats
mu = 0
sigma = 1
probability = stats.norm.cdf(1, mu, sigma)
print("P(X <= 1) for N(0, 1):", probability)

P(X <= 1) for N(0, 1): 0.8413447460685429
